# Generated by Django 4.2.27 on 2026-02-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('drafter', '담당(기안자)'), ('admin', '총무'), ('chairman', '회장')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'is_active'], name='approvals_v_role_b76312_idx'), models.Index(fields=['role', 'department', 'name'], name='approvals_v_role_94506a_idx')],
            },
        ),
    ]
