# Generated by Django 4.2.27 on 2026-02-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalrequest_id'),
        ('approvals_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRouteInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('draft', '작성중'), ('in_progress', '진행중'), ('rejected', '반려'), ('completed', '완료')], default='draft', max_length=20)),
                ('current_order', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_v2', to='approvals.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRouteStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('acted_device', models.CharField(blank=True, default='', max_length=50)),
                ('acted_anon_id', models.CharField(blank=True, default='', max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals_v2.approvalrouteinstance')),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'order'], name='approvals_v_route_i_c30864_idx'), models.Index(fields=['role', 'state'], name='approvals_v_role_70f9af_idx')],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
