# Generated by Django 4.2.27 on 2026-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_v2', '0002_approvalrouteinstance_approvalroutestepinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalroutestepinstance",
            name="reject_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]