# Generated by Django 4.2.27 on 2026-02-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_v2', '0003_add_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalroutestepinstance',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/steps/'),
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/recipients/'),
        ),
    ]
