# Generated by Django 4.2.27 on 2026-02-10 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalrequest_id'),
        ('approvals_v2', '0004_approvalroutestepinstance_stamp_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='approval_v2/attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_attachments', to='approvals.approvalrequest')),
            ],
        ),
    ]
