# Generated by Django 4.2.27 on 2026-02-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals_v2', '0005_approvalattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramrecipient',
            name='role',
            field=models.CharField(choices=[('drafter', '담당(기안자)'), ('admin', '총무'), ('chairman', '회장'), ('auditor', '감사')], max_length=20),
        ),
    ]
