# Generated by Django 5.2.9 on 2025-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_auto_20251215_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
